//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSistemi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kitap()
        {
            this.Tbl_Hareket = new HashSet<Tbl_Hareket>();
        }
    
        public int Id { get; set; }
        public string Kitapad { get; set; }
        public Nullable<int> Katid { get; set; }
        public Nullable<int> Yazarid { get; set; }
        public string Sayfasayisi { get; set; }
        public string Basyımyılı { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Yayinevi { get; set; }
        public string Foto { get; set; }
        public string Detay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hareket> Tbl_Hareket { get; set; }
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        public virtual Tbl_Yazar Tbl_Yazar { get; set; }
    }
}
