//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSistemi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hakkımızda
    {
        public int Id { get; set; }
        public string icerik1 { get; set; }
        public string icerik2 { get; set; }
    }
}
