//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSistemi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ceza
    {
        public int Id { get; set; }
        public Nullable<int> uyeid { get; set; }
        public Nullable<System.DateTime> Baslangic { get; set; }
        public Nullable<System.DateTime> Bitis { get; set; }
        public Nullable<decimal> Paracezası { get; set; }
        public Nullable<int> Hareketid { get; set; }
    
        public virtual Tbl_Hareket Tbl_Hareket { get; set; }
        public virtual Tbl_Uye Tbl_Uye { get; set; }
    }
}
