//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSistemi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Hareket()
        {
            this.Tbl_Ceza = new HashSet<Tbl_Ceza>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Uyeid { get; set; }
        public Nullable<int> Kitapid { get; set; }
        public Nullable<int> Perid { get; set; }
        public Nullable<System.DateTime> Alistarihi { get; set; }
        public Nullable<System.DateTime> İadetarih { get; set; }
        public Nullable<decimal> Para { get; set; }
        public Nullable<System.DateTime> Teslimtarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ceza> Tbl_Ceza { get; set; }
        public virtual Tbl_Kitap Tbl_Kitap { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
        public virtual Tbl_Uye Tbl_Uye { get; set; }
    }
}
